### ISSUE TITLE
Implement gaussian elimination

### ISSUE THREAD

**Issue by philsupertramp** [philsupertramp/game-math#8]
Gaussian elimination is an algorithm in linear algebra for solving a system of linear equations.

depends on #7 

Matlab implementation
[gaussPivot.m.txt](https://github.com/philsupertramp/game-math/files/5608165/gaussPivot.m.txt)

Test file:
[Test_gauss.m.txt](https://github.com/philsupertramp/game-math/files/5608167/Test_gauss.m.txt)

**Comment by joshinils** [comment]
depends on itself?
